name: milkminder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  google_fonts: ^6.2.1
  slider_button: ^2.1.0
  smooth_page_indicator: ^1.2.0+3
  card_swiper: ^3.0.1
  cloud_firestore: ^5.5.0
  curved_navigation_bar: ^1.0.6
  expansion_tile_card: ^3.0.0
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  intl: ^0.19.0
  pie_chart: ^5.4.0
  easy_date_timeline: ^1.1.3
  fl_chart: ^0.69.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  shared_preferences: ^2.3.3
  scratcher: ^2.0.0
  flutter_slider_drawer: ^2.1.3
  pdf: ^3.11.1
  printing: ^5.13.4
  open_file: ^3.5.10
  confetti: ^0.8.0
  dropdown_model_list: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "./assets/play_store_512.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "./assets/play_store_512.png"

flutter:
  uses-material-design: true
  assets:
      - assets/
      - assets/Roboto-Regular.ttf
